### ISSUE TITLE
Cannot pull docker images from nexus.engageska-portugal.pt

### ISSUE THREAD

**Issue by ahoffstadt** [ska-telescope/ska-docker#18]
Hello,

I am trying to setup the docker environment, but the images fail to pull from the server, eventually timing out:
The frist one that fails is:
nexus.engageska-portugal.pt/ska-docker/tango-db:latest

pings also timeouts.

**Comment by jbmorgado** [comment]
Hi @ahoffstadt 

This repo is very outdated. Please check https://github.com/ska-telescope/tango-example for an updated starting point.

We should probably archive these, but since our GitHub account is only a mirror for our GitLab working space, I think we have no automated way of getting rid of the deprecated repos here.
